boilerplate_phrases:
    # Completion & Progress Instructions
    - "after you complete this activity"
    - "return to this page to select mark complete"
    - "for completion credit"
    - "you will get completion credit in the ibm security learning academy"
    - "you have the option to complete the web development fundamentals courses"
    - "after completing this course, you should be able to"
    - "after completing cybersecurity fundamentals, you should be able to"
    - "you will find short instructional content offerings"
    - "you will be prompted to log in"
    - "for first time users, your user id must be the email address linked to your ibmid"
    - "complete the following modules to earn an industry-recognized ibm skillsbuild digital credential"
    - "complete this course to earn the cybersecurity fundamentals badge"
    # Introductory/Descriptive
    - "about this learning activity"
    - "about this digital credential"
    - "disclaimer"
    - "learning outcomes"
    - "level: beginner"
    - "presentation slides"
    - "resources"
    - "prerequisite: none"
    - "there is an updated version of this course in the following"
    - "there is an updated version of this course"
    # Subtitles / Language Settings
    - "note: on the video toolbar"
    - "go to settings"
    - "select subtitles"
    - "select english"
    - "auto-translate"
    - "enable subtitles"
    - "language of your choice"
    - "from the drop-down"
    - "this activity is available only in english"
    - "this newly designed experience is"
    # Legal Disclaimers
    - "any presentation by the presenting lawyers"
    - "should not be considered or construed as legal advice"
    - "receipt of it does not constitute an attorney-client relationship"
    - "the contents of this document are intended for general information purposes only"
    # Badging / Enrolment
    - "badge opportunity"
    - "badges:"
    - "click enroll"
    - "click the enroll me button"
    - "click here to take it"
    - "select enroll"
    - "select start tracking progress"
    - "complete the courses in order"
    - "courses: 3"
    - "you agree to the following"
    - "to enroll in this learning plan and get started"
    # Introductory Fluff
    - "have fun exploring"
    - "curious about tech, but not sure where to focus"
    - "in this recorded webinar, you will"
    - "webinar summary"
    - "what you’ll learn"
    # Course Provider Mentions
    - "this article is presented by indeed career guide"
    - "this course is presented by openclassrooms"
    - "this course is presented by w3schools"
    - "this resource is presented by w3schools"
    - "this video is presented by 365 data science"
    - "this video is presented by edureka"
    - "this video is presented by simplilearn"
    - "this video is presented by freecodecamp.org"
    - "presented by professor messer"
    - "presented by red hat"
    - "this learning activity is presented by khan academy"
    - "this course requires you register for an ibmid to access"
    - "it is presented by edureka"
    # Miscellaneous
    - "the topics include"
    - "this is a curation of eight course units"
    - "overview of data tools and languages"
    - "duration: 7 hours, 10 minutes"
    - "duration: complete the activities in this course and earn 30 minutes of learning credit!"
    - "the content is offered in english"
    - "languages:"
    - "language:"
    - "note:"
    # Specific Redundant Phrases
    - "> when you complete all courses, be sure to return to page to select mark complete for completion credit on ibm skillsbuild"
    - "start with the get the details! resource to discover if this program is right for you"
    - "getting started in cybersecurity is ideal for individuals in non-technical job positions"
    - "technical introduction to cybersecurity is ideal for individuals in technical roles"
    - "you will need to register for a free account"
    - "get a feel for cybersecurity as a career"
    - "and then select auto-translate to enable subtitles in a language of your choice from the drop-down"